# Generated by Django 5.1.6 on 2025-02-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
